[package]
name = "pitest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
num-bigfloat = "1.6.2"
num-bigint = "0.4"
num-iter = "0.1"
